import numpy as np
import healpy as hp
import os
from google.colab import drive

# 1. Connect to Google Drive
drive.mount('/content/drive', force_remount=True)

# 2. Fixed Target Configurations
NSIDE = 128
PIXEL_ALVO = 88856
ACHATAMENTO = 0.95
RAIO_GRAUS = 4
THRESHOLD = 3.88  # Real ring significance
TOTAL_SIMULACOES = 10000
INTERVALO_LOG = 500

PATH_DRIVE = "/content/drive/MyDrive/CCC_Planck/"
MAPA_LOCAL_PATH = PATH_DRIVE + "Planck_CMB.fits"
FILE_NAME = PATH_DRIVE + "statistical_validation_ring.txt"

if os.path.exists(FILE_NAME): 
    os.remove(FILE_NAME)

def log_e_print(texto):
    print(texto)
    with open(FILE_NAME, "a") as f:
        f.write(texto + "\n")

log_e_print("[SYSTEM] Starting Isolated Statistical Verification...")
log_e_print(f"[TARGET] Pixel: {PIXEL_ALVO} | Radius: {RAIO_GRAUS}° | Ellipticity: {ACHATAMENTO}")

# 3. Load the real map to extract the Cl (Power Spectrum)
if not os.path.exists(MAPA_LOCAL_PATH):
    raise FileNotFoundError(f"Error: The map 'Planck_CMB.fits' was not found in '{PATH_DRIVE}'")

mapa = hp.read_map(MAPA_LOCAL_PATH, field=0, verbose=False)
mapa = hp.pixelfunc.ud_grade(mapa, NSIDE)
CL_REAL = hp.anafast(mapa)
log_e_print("[SYSTEM] Angular power spectrum (Cl) successfully generated from Planck data.")

# 4. GEOMETRIC PRE-COMPUTATION (Optimization)
theta_0, phi_0 = hp.pix2ang(NSIDE, PIXEL_ALVO)
raio_a = np.radians(RAIO_GRAUS)
raio_b = raio_a * ACHATAMENTO

listas_de_bordas_precomputadas = []
raio_maximo_busca = raio_a * 1.1 * 1.5
vizinhos = hp.query_disc(NSIDE, hp.pix2vec(NSIDE, PIXEL_ALVO), raio_maximo_busca)

theta, phi = hp.pix2ang(NSIDE, vizinhos)
d_theta = theta - theta_0
d_phi = phi - phi_0

for angulo_alpha in [0, np.pi/4, np.pi/2, 3*np.pi/4]:
    bordas_do_angulo = []
    for mult in [0.9, 1.0, 1.1]:
        r_a = raio_a * mult
        r_b = raio_b * mult
        
        termo1 = ((d_theta * np.cos(angulo_alpha) + d_phi * np.sin(theta_0) * np.sin(angulo_alpha))**2) / (r_a**2)
        termo2 = ((-d_theta * np.sin(angulo_alpha) + d_phi * np.sin(theta_0) * np.cos(angulo_alpha))**2) / (r_b**2)
        distancia_elipse = termo1 + termo2
        
        borda_bool = (distancia_elipse >= 0.95) & (distancia_elipse <= 1.05)
        pixels_borda = vizinhos[borda_bool]
        if len(pixels_borda) > 10:
            bordas_do_angulo.append(pixels_borda)
             
    if len(bordas_do_angulo) == 3:
        listas_de_bordas_precomputadas.append(bordas_do_angulo)

log_e_print("[SYSTEM] Ellipse geometry pre-computed in memory. Launching Monte Carlo loop...")

# 5. MONTE CARLO LOOP
alarmes_falsos_totais = 0

for sim in range(1, TOTAL_SIMULACOES + 1):
    mapa_fake = hp.synfast(CL_REAL, nside=NSIDE, verbose=False)
    var_bg_fake = np.var(mapa_fake)
    
    sinal_detectado_na_simulacao = False
    
    for bordas_do_angulo in listas_de_bordas_precomputadas:
        variancias_aneis = [np.var(mapa_fake[p_borda]) for p_borda in bordas_do_angulo]
        
        media_var = np.mean(variancias_aneis)
        sigma_calculado = media_var / var_bg_fake
        
        if sigma_calculado > THRESHOLD:
            sinal_detectado_na_simulacao = True
            break 
            
    if sinal_detectado_na_simulacao:
        alarmes_falsos_totais += 1
        
    if sim % INTERVALO_LOG == 0:
        p_value_parcial = alarmes_falsos_totais / sim
        log_e_print(f"[CHECKPOINT] Simulations Completed: {sim}/{TOTAL_SIMULACOES}")
        log_e_print(f"  -> False alarms generated by noise: {alarmes_falsos_totais}")
        log_e_print(f"  -> Partial P-value registered: {p_value_parcial:.6f}")
        log_e_print("-" * 50)

# 6. FINAL REPORT CLOSURE
p_value_final = alarmes_falsos_totais / TOTAL_SIMULACOES
probabilidade_ruido = p_value_final * 100

log_e_print("\n" + "="*60)
log_e_print("STATISTICAL CRITICAL VERDICT (MONTE CARLO)")
log_e_print(f"• Target: Pixel {PIXEL_ALVO} (Ellipticity {ACHATAMENTO} / Radius {RAIO_GRAUS}°)")
log_e_print(f"• Total control universes simulated: {TOTAL_SIMULACOES}")
log_e_print(f"• Iterations where noise replicated the structure: {alarmes_falsos_totais}")
log_e_print(f"• Final P-value: {p_value_final:.6f}")
log_e_print(f"• Probability of random stochastic coincidence: {probabilidade_ruido:.4f}%")

if alarmes_falsos_totais == 0:
    log_e_print("\nCONCLUSION: SCIENTIFIC SIGNIFICANCE CONFIRMED.")
    log_e_print("The signal resisted 10,000 control universes without a single replication by noise.")
else:
    log_e_print("\nCONCLUSION: STOCHASTIC FLUCTUATION DETECTED.")
    log_e_print(f"The standard inflation model emulated the signature in {alarmes_falsos_totais} iterations.")
log_e_print("="*60)

print("[SYSTEM] Process completed successfully. File 'statistical_validation_ring.txt' saved to Drive.")